### ISSUE TITLE
Resuming from checkpoint is ignored?

### ISSUE THREAD

**Issue by rdrighetto** [MLI-lab/DeepDeWedge#6]
When trying to resume `ddw fit-model` from a previous checkpoint, it seems to ignore it and start fitting from scratch again. I am adding the `resume-from-checkpoint` line to my `config.yaml` file:

```
fit_model:
    unet_params_dict:
      chans: 32
      num_downsample_layers: 3
      drop_prob: 0.1
    adam_params_dict: 
      lr: 0.0004
    num_epochs: 600
    batch_size: 10
    update_subtomo_missing_wedges_every_n_epochs: 10
    check_val_every_n_epochs: 10
    save_n_models_with_lowest_val_loss: 5
    save_n_models_with_lowest_fitting_loss: 5
    save_model_every_n_epochs: 50
    logger: "csv"
    resume-from-checkpoint: "ddw_imod/logs/version_0/checkpoints/epoch/epoch=399.ckpt"
```

I know it's starting from scratch because the fitting loss at this epoch was 0.14867860078811646 in the previous run (which crashed), but upon starting this new run it says the fitting loss is 0.1634301096200943 in the first epoch. Does that make sense?

Thank you!
